Update README.md
saadpasta/developerFolio pull request #236
Opened 2020-08-27 03:17 UTC by lARSHADl

2020-08-28 13:22 UTC, naveen521kk requested changes

2020-08-28 13:22 UTC, naveen521kk commented on README.md
> +Set `showGithubProfile` to true or false to show Contact Profile using Github,Default is set as false.
I think the previous one correct.

2020-08-29 18:36 UTC, naveen521kk requested changes
Sorry for delay :(

2020-08-29 18:36 UTC, naveen521kk commented on README.md
> +Note: Open Source Projects section only show pinned items of your Github. If you are seeing [this](https://i.imgur.com/Hj6mu1K.png), please follow this
**Suggestion**: Embed the image instead of saying, if you see this.

2020-08-30 05:10 UTC, kartikcho requested changes

2020-08-30 05:10 UTC, kartikcho commented on README.md
> +Note: Open Source Projects section only show pinned items of your Github. If you are seeing [this](https://i.imgur.com/Hj6mu1K.png), please follow this
Change `follow this` to `follow these`.

2020-08-30 05:10 UTC, kartikcho commented on README.md
>  [Instructions](https://docs.github.com/en/enterprise/2.13/user/articles/pinning-items-to-your-profile).
Remove capitalized `I` in Instructions.

2020-09-07 13:12 UTC, naveen521kk commented
Any update on this @lARSHADl ?

2020-09-07 14:45 UTC, lARSHADl commented
Sorry guys new to github and this was my first commit

2020-09-07 14:48 UTC, naveen521kk commented on README.md
> +Set `showGithubProfile` to true or false to show Contact Profile using Github,Default is set as false.
@lARSHADl Could you revert this to how it was before?

2020-09-07 14:52 UTC, lARSHADl commented
Done !

-------- Original Message --------
On Sep 7, 2020, 8:18 PM, Naveen M K wrote:

> @naveen521kk commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [README.md](https://github.com/saadpasta/developerFolio/pull/236#discussion_r484475226):
>
>> @@ -99,9 +99,9 @@ Note: Instead of creating a .env file, you can just run this command "cp env.exa
>    REACT_APP_GITHUB_TOKEN = "YOUR GITHUB TOKEN HERE"
>  ```
>
> -Set `showGithubProfile` to true or false to show Contact Profile using Github, defaults to false.
> +Set `showGithubProfile` to true or false to show Contact Profile using Github,Default is set as false.
>
> [@lARSHADl](https://github.com/lARSHADl) Could you revert this to how it was before?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, [view it on GitHub](https://github.com/saadpasta/developerFolio/pull/236#discussion_r484475226), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AK3533HVPHJYULGNW2V7KCLSETXDXANCNFSM4QMP5PBQ).

2020-09-07 15:07 UTC, naveen521kk commented on README.md
> +
Why not use markdown like
```suggestion
![Error](https://i.imgur.com/Hj6mu1K.png)
```

2020-09-07 15:08 UTC, naveen521kk commented on README.md
>  [Instructions](https://docs.github.com/en/enterprise/2.13/user/articles/pinning-items-to-your-profile).
As @kartikcho said do 
```suggestion
[instructions](https://docs.github.com/en/enterprise/2.13/user/articles/pinning-items-to-your-profile).
```

2020-09-07 16:38 UTC, lARSHADl commented
Will change to the last check point with ! Markdown .

2020-09-08 07:13 UTC, kartikcho approved these changes
Hey @lARSHADl, thanks for opening a PR for this, everything looks good now!

2020-09-10 17:47 UTC, lARSHADl commented
Is there anything that's bothering you, please feel free to suggest  ?

2020-09-10 18:50 UTC, naveen521kk approved these changes
Sorry for the delay!

2020-09-10 18:51 UTC, merged

2020-09-10 18:53 UTC, naveen521kk commented
@all-contributors please add @lARSHADl for doc