Table of Contents added to README.md
saadpasta/developerFolio pull request #256
Opened 2020-10-04 13:08 UTC by palak-sethi

#239 I had to remove the emojis from some headings because they couldn't be included in the internal link. 
However, if the emojis are necessary then i can use anchor tags to name the sections and then link them.

2020-10-04 13:13 UTC, naveen521kk requested changes

2020-10-04 13:13 UTC, naveen521kk commented on README.md
> +-[Contributors](#contributors)
The markdown is ill-formatted.
```suggestion
## Table of Contents
- [Sections](#sections)\
- [Getting Started](#getting-started)\
- [How to Use](#how-to-use)\
- [Github Setup](#github-setup-for-open-source-projects)\
- [Change and Customize](#change-and-customize-every-section-according-to-your-need)\
- [Deployment](#deployment)\
- [Technologies Used](#technologies-used)\
- [Illustrations](#illustrations)\
- [For the Future](for-the-future)\
- [Project Maintainers](#project-maintainers)\
- [Contributors](#contributors)
```

2020-10-04 13:54 UTC, palak-sethi commented
Alright, I'll do the requested changes

2020-10-04 14:29 UTC, kartikcho requested changes
Things look good, just need to address a few nits and we're good to go!

2020-10-04 14:29 UTC, kartikcho commented on README.md
> +## Table of Contents
![image](https://user-images.githubusercontent.com/48270786/95018191-bdcced00-067b-11eb-9eee-174548b4c6fd.png)

This is how the index looks like right now, you've left `\` in front of the text.

2020-10-04 14:29 UTC, kartikcho commented on README.md
> +- [Github Setup](#github-setup-for-open-source-projects)\
We should change this to `Linking Portfolio to GitHub` and appropriately change the heading of the section to something similar too.

2020-10-04 14:31 UTC, kartikcho commented on README.md
> +- [Project Maintainers](#project-maintainers)\
Let's remove this and just keep `Contributors` that is linked to `#project-maintainers` to avoid differentiating between all contributors!

2020-10-04 16:36 UTC, kartikcho approved these changes
Check out my comments for some nits, everything else is good!

2020-10-04 16:36 UTC, kartikcho commented on README.md
> +## Linking portfolio to Github
nit: Capitalize `P` here

2020-10-04 16:36 UTC, kartikcho commented on README.md
> +## Technologies used
Same here with `U`

2020-10-04 16:44 UTC, palak-sethi commented
Thanks :)

2020-10-05 18:04 UTC, naveen521kk approved these changes
LGTM!

2020-10-05 18:05 UTC, merged