Added error messages for twitter, podcast & project component
saadpasta/developerFolio pull request #258
Opened 2020-10-05 07:41 UTC by SamratDe

Resolves #212

- Added error messages in Podcast and twitter component.
- Changed already existing error messages in Projects and Profile component.
- fixed a prop name in GithubProfileCard.

2020-10-05 08:32 UTC, naveen521kk requested changes
Please don't use prettier or any code formatter. It would make things hard to review. That can be used only after prettier is set up by #107 
Revert everything because of code formatter.

2020-10-05 18:03 UTC, naveen521kk commented
Ok we can close that PR. Also, I will set up prettier.

2020-10-16 10:44 UTC, kartikcho commented
Are you still working on this @SamratDe ?

2020-10-16 15:41 UTC, SamratDe commented
@kartikcho I have Added error messages for Podcast and Twitter section. Review was requested to not use the prettier formatter. But then @naveen521kk said that he will set up prettier. So I haven't change anything in the pull request. Can't it be merged ?

2020-10-16 17:59 UTC, kartikcho commented
The Prettier PR will reformat the whole codebase with it's rules so if we merge a PR with it's own Prettier config, it'll mess and overcomplicate the existing PRs. Also, in general it's a bad practice to have non-uniform formatted codebase. 
Address the changes requested and we can get this merged soon!

2020-10-17 07:25 UTC, SamratDe commented
Oh Ok. I will remove the prettier config from those files.

2020-10-24 12:38 UTC, SamratDe commented
@kartikcho I have made the required changes. Please review it.

2020-10-24 14:01 UTC, kartikcho commented
Hey @naveen521kk could you have a look? I won't be on a system for a few days but don't want to delay this PR.
Thanks! 

(Code reviews from the GitHub app are a pain lol)

2020-10-24 14:25 UTC, naveen521kk requested changes
There were many things which isn't related to this PR.  Could you fix that?

2020-10-24 14:25 UTC, naveen521kk commented on package.json
> +    "react-scripts": "^3.4.3",
Can you remove these changes? This is not related to this PR.

2020-10-24 14:25 UTC, naveen521kk commented on src/components/githubProfileCard/GithubProfileCard.js
> +import { Fade } from 'react-reveal'
Again these changes are not related to this PR.

2020-10-24 14:25 UTC, naveen521kk commented on src/components/githubProfileCard/GithubProfileCard.js
> +    prof.hireable = 'No'
Again, not related to this PR.

2020-10-24 14:25 UTC, naveen521kk commented on src/components/githubProfileCard/GithubProfileCard.js
> +              </p>
Again not related to this PR.

2020-10-24 14:25 UTC, naveen521kk commented on src/components/githubProfileCard/GithubProfileCard.js
> +                Open for opportunities: {prof.hireable}
Again not related to this PR.

2020-10-24 14:25 UTC, naveen521kk commented on src/components/githubProfileCard/GithubProfileCard.js
> +            />
Not related to this PR.

2020-10-24 14:25 UTC, naveen521kk commented on src/containers/podcast/Podcast.js
> +import { Fade } from 'react-reveal'
Why are trailing `;` removed?

2020-10-24 14:25 UTC, naveen521kk commented on src/containers/podcast/Podcast.js
> +      console.log("Can't load Podcast. Check podcast link.")
this could happen because of any adblocker also. please log that also.

2020-10-24 14:25 UTC, naveen521kk commented on src/containers/profile/Profile.js
> +import Loading from '../loading/Loading'
Again not related to this PR.

2020-10-24 14:25 UTC, naveen521kk commented on src/containers/profile/Profile.js
> +)
Again not related to this PR.

2020-10-24 14:25 UTC, naveen521kk commented on src/containers/profile/Profile.js
> +      uri: 'https://api.github.com/graphql',
again not related.

2020-10-24 14:26 UTC, naveen521kk commented
Can you fix conflicts?

2020-10-24 16:13 UTC, SamratDe commented
@naveen521kk Most of the requested changes are indentation (which I made proper for better understanding of the code) and removed semicolon. Do I need to rollback all these changes ? 😅

2020-10-24 16:33 UTC, naveen521kk commented
>  Do I need to rollback all these changes ? 

Yes, you shouldn't be something which should not be done( I mean it's not this PR open a new one if you want to). Because that just spoils git history and that is something unexpected and shouldn't happen. What you should do it just follow the title of the PR because that would be added as a single commit when merged.

2020-10-29 10:46 UTC, kartikcho commented
Hey @SamratDe any updates?

2020-10-29 14:01 UTC, SamratDe commented
Sorry @kartikcho I am really busy with my final year project, internship and college and I will be busy for at least few weeks. You can close this pull request. I will return as soon as I finish my other works and look for other issues to contribute. Now that I know the code repository and how it is maintained, it will be easy for me. Sorry again, for leaving in the middle.

2020-10-29 14:08 UTC, MuhammadHasham23 commented
Can I take it from here @kartikcho ?

2020-10-29 14:42 UTC, kartikcho commented
Sure @MuhammadHasham23

2020-11-07 04:25 UTC, closed without merging