Added shadow on hover to all cards.
saadpasta/developerFolio pull request #324
Opened 2021-02-08 12:50 UTC by jayhawk24

Resolves Issue #306.
Added smooth transition to github cards and also box-shadow in dark mode.
Added box-shadow to achievement cards in dark mode.

2021-02-08 18:00 UTC, kartikcho requested changes
Just need to address one minor thingy and we're good to go!

2021-02-09 05:40 UTC, jayhawk24 commented on src/components/achievementCard/AchievementCard.css
> +}
okay  cool.

2021-02-09 06:30 UTC, jayhawk24 reviewed
Works on both modes (light and dark)

2021-02-09 15:10 UTC, kartikcho approved these changes
Everything looks good, a great PR! Thanks!

2021-02-09 15:10 UTC, merged

2021-02-09 15:18 UTC, kartikcho commented
@allcontributors please add @jayhawk24 for code