docs: add info about the new profile setup
saadpasta/developerFolio pull request #343
Opened 2021-03-22 13:05 UTC by naveen521kk

about #333
fixes #342
encourage using Github Actions more about #226 because that would simply things

2021-03-24 13:58 UTC, kartikcho requested changes
I think our docs have come a long way since we started and are really descriptive now 🚀 

Need to address the minor change and we're good to go.

Also, the Vercel Preview deployments logs say it's missing env variables.
@saadpasta have you set them since this change was added and does this only affect preview deps?

2021-03-24 13:58 UTC, kartikcho commented on README.md
> +Their is a [CRON setup](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events) up so that it deploys your site every week, so that once you update your profile o
Change this to start with: 'A configurable [CRON Job]() is setup which deploys your site....'
Maybe move the linked blog as a link like '...see [this guide]() on how to do that'

2021-03-24 15:46 UTC, kartikcho approved these changes

2021-03-25 11:59 UTC, saadpasta commented on README.md
> +
I think we should also add why we need to deploy the website every week or when should the user trigger the deployment manually it's not that much clear

2021-03-25 12:00 UTC, saadpasta commented
@kartikcho env added on vercel and preview for deployment is also fixed I don't need to approve it every time I guess (not sure about this but let see 🤞 )

2021-03-25 12:02 UTC, saadpasta commented
In other news guys @naveen521kk  @kartikcho. 

Clever Programmer the guy with almost 1 Million subscribers using DeveloperFolio to teach his students about React and JavaScript in one of his free courses. 

Video: https://www.youtube.com/watch?v=86F11Y56wmI
Clever Programmer Repo: https://github.com/CleverProgrammers/portfolio-react-cp

2021-03-25 12:03 UTC, saadpasta commented
All props to you guys for maintaining the project so well. Thanks guys ❤️

2021-03-25 12:06 UTC, kartikcho commented
Wow, this is huge 🎉 
Happy to know this project is gaining more and more recognition!

2021-03-26 08:37 UTC, naveen521kk commented
@saadpasta is it fine to merge this?

2021-03-26 09:30 UTC, saadpasta approved these changes
LGTM 👍

2021-03-26 09:31 UTC, merged