feat: add icon for dark and light theme
saadpasta/developerFolio pull request #530
Opened 2022-10-01 10:46 UTC by Dun-sin

## closes #528 

## Changes proposed
- Add icons ☀️, 🌜 for light and dark mode respectively

## Screenshot
![image](https://user-images.githubusercontent.com/78784850/193405901-a07fbdb9-bcfd-425b-aa1e-0478b1e517e9.png)

2022-10-01 16:10 UTC, kartikcho commented
@Dun-sin is it possible to use emojis using the existing `react-easy-emoji` dependency? This way the emojis would be consistent across platforms.

Also minor nit but there's a very little 1px space in day mode slider state (see gif below). Making the switch go slightly extra behind in day mode slider state should fix it (similar to night mode state)

![Screen Cast 2022-10-01 at 9 37 24 PM](https://user-images.githubusercontent.com/48270786/193418251-9b5d5b50-044c-4c6f-b0c9-8b6573f2b793.gif)

2022-10-01 16:14 UTC, Dun-sin commented
I don't think there's a way to style a before element in react JSX, i looked for a solution and couldn't find one, maybe I can keep trying to find a solution, if you want. 

Also the 1px space isn't part of my PR, if you checked my files I never touched anything else, maybe it should be a separate issue if you want a fix for it

2022-10-01 16:23 UTC, kartikcho commented
> I don't think there's a way to style a before element in react JSX

Have you tried setting the content in `style={{}}`? This should be a solved problem I think

> Also the 1px space isn't part of my PR

Yeah I know it isn't a part of your PR but we can fix that with this one too. If you want to create a separate issue and a PR for it, that's alright, just add me as the reviewer so I dont miss it.

2022-10-01 16:24 UTC, Dun-sin commented
> > I don't think there's a way to style a before element in react JSX
> 
> Have you tried setting the content in `style={{}}`? This should be a solved problem I think
> 
> > Also the 1px space isn't part of my PR
> 
> Yeah I know it isn't a part of your PR but we can fix that with this one too. If you want to create a separate issue and a PR for it, that's alright, just add me as the reviewer so I dont miss it.

Yeah I know about the style, but I need to use before pseudoclass, and I don't think to can assess it that way.

I would rather create a new issue

2022-10-01 16:45 UTC, Dun-sin commented
@kartikcho what do you think, should I leave it or try to still figure it out

2022-10-02 10:09 UTC, kartikcho commented
@Dun-sin I did a quick search and it looks like it is possible with two solutions that you could try out. These methods are also new to me so I'm excited to see this work!

- [Using a variable for the content in CSS](https://stackoverflow.com/a/65690431)
- [Create a new pseudo element via react](https://stackoverflow.com/a/28269950)

2022-10-03 10:36 UTC, Dun-sin commented
> @Dun-sin I did a quick search and it looks like it is possible with two solutions that you could try out. These methods are also new to me so I'm excited to see this work!
> 
>     * [Using a variable for the content in CSS](https://stackoverflow.com/a/65690431)
> 
>     * [Create a new pseudo element via react](https://stackoverflow.com/a/28269950)

I saw the second resource, but I didn't want to create a new element

2022-10-04 18:22 UTC, Dun-sin reviewed
Seems fine now, let me know what you think

2022-10-05 13:52 UTC, kartikcho requested changes

2022-10-05 13:52 UTC, kartikcho commented on src/components/ToggleSwitch/ToggleSwitch.js
> +  console.log(isChecked)
leftover log

2022-10-05 13:53 UTC, Dun-sin commented on src/components/ToggleSwitch/ToggleSwitch.js
> +        <span className="emoji">{isChecked ? themeStyle["--dark-mode"] : themeStyle["--light-mode"]}</span>
Trying to keep a clean code, but I can take it off if you want

2022-10-07 09:19 UTC, Dun-sin reviewed
done as you asked, tell me what you think

2022-10-09 08:32 UTC, kartikcho commented on src/components/ToggleSwitch/ToggleSwitch.js
> +        <span className="emoji">{isChecked ? themeStyle["--dark-mode"] : themeStyle["--light-mode"]}</span>
I don't see how creating 2 abstractions for a simple conditional is clean code. Thanks for simplifying it

2022-10-09 08:33 UTC, kartikcho approved these changes
Looks good!

2022-10-09 08:34 UTC, merged

2022-10-09 08:35 UTC, kartikcho commented
@allcontributors please add @Dun-sin for code